project:
  type: website

website:
  title: "FØS8300"
  navbar:
    left:
      - href: index.qmd
        text: FØS8300
      - href: kort_innforing/index.qmd
        text: Kort innføring

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

